radicle-dev/radicle-contracts

.solhint.json, contracts/Rad.sol, contracts/VRad.sol, test/vrad.test.ts
```
/// The vRad token.
///
/// This contract implements a simple vesting token (vRad) that can be redeemed
/// for an equal amount of Rad when the vesting period is over.
///
/// The general idea is the following:
///
/// 1. The contract is initialized with a "grantor" who has the right
///    to grant vRad to an address. The contract starts out with a zero
///    balance.
/// 2. The contract supply is expanded via `expandTokenSupply`. With this
///    method, the sender can transfer Rad to mint an equal amount of vRad
///    into the contract's supply. The contract now holds an equal amount of
///    Rad and vRad.
/// 3. When the grantor wants to grant tokens to an address, they call
///    `allocateTokens`. This simply transfers vRad from the contract
///    to the "grantee", and …
```
=> Rad token vesting

package.json
We can now install and use this package with yarn or npm from a git
repository.
=> Package can be used as a dependency

.buildkite/pipeline.yaml, README.md, ci/run, package.json, src/deploy.ts, src/ens.ts, src/index.ts, test/registrar.test.ts, tsconfig.json
* Add a function `deployDev` that deploys development contract infrastructure.
* Use `deployDev` in tests
* Expose `deployDev` as part of the package
* Add ENS helper functions to better deal with name and label hashes
* Add package tarball to build artifacts so we can use it from other projects (i.e. upstream)
=> Add function to deploy contracts for development

contracts/Exchange.sol, contracts/Registrar.sol, src/deploy.ts, src/index.ts, test/registrar.test.ts, test/support.ts, test/vrad.test.ts
This sets up a deploy function, `deployAll` that deploys the bytecode of ENS and Uniswap, sets up proper liquidity pairs for Uniswap and hooks everything up with our contract. This allows us to test everything using the "real" contracts, instead of the dummy ones.
As you'll notice, the registration fee taken from the Uniswap price oracle is always going to be slightly lower than expected, eg. given a 1:1 liquidity ratio, the price of 1000 USD will be ~999 ETH.
=> Deploy uniswap/ens backed contracts

package.json
With this change the package can be installed as a git dependency with Yarn. See https://github.com/yarnpkg/yarn/issues/5235#issuecomment-571206092
=> Add 'prepare' script so package can be installed as git dep

.eslintrc.js, .gitignore, buidler.config.ts, package.json, src/deploy.ts, test/attestations.test.ts, test/pool.test.ts, test/vrad.test.ts, yarn.lock
We add TypeScript contract bindings for the Web3 library. This requires
us to restructure the output folders for bindings.
=> Add web3 contract bindings

contracts/Org.sol, test/org.test.ts, test/support.ts
Addresses parts of #21 
This changeset doesn't implement the full org functionality; only project anchoring. The rest will come in subsequent changesets.
An org contract is meant to be deployed per org. This allows orgs to have an address, and makes the contract a little simpler.
=> Implement basic orgs

.eslintrc.js, buidler.config.ts, src/deploy.ts, test/pool.test.ts, tsconfig.eslint.json
We add all recommended lints that require type checking. This allows us to catch issues with promises.
=> Add lints for type checking

contracts/Pool.sol, test/support.ts
Reduces gas usage when adding a receiver. It reduces edited slots per receiver from 4 to 2 when starting or stopping a payment. On the other hand it slightly increases gas usage while collecting, because more slots need to accessed.
When I have more time I need to dive deeper to understand the costs, there are many mysterious gas sinks, which I can't explain. E.g. reading a variable from a storage map costing 1000 gas. Or deletion of slots in a loop, which when commented out increases gas usage by just a few thousand instead of tens of thousands.
=> Add nextCycle to receiver deltas

test/pool.test.ts
The test tools have grown a lot recently in an organic way. Some of them require raw `address`es, some `PoolUser`s, there's also a lot of boilerplate around accessing `PoolUser`s' fields. This PR aims at cleaning it up by moving most of the tools from functions to `PoolUser`s' methods.
=> Encapsulate pool test utils

contracts/Pool.sol, contracts/PoolTest.sol, test/pool.test.ts
The first step toward https://github.com/radicle-dev/radicle-contracts/issues/16. Alters the `ReceiverWeights` iterator by making its API dependant not on weight, but on receiver address. It's also tighter with memory usage and simpler when it comes to the `view` iterator.
=> Rework ReceiverWeights iterator

contracts/Pool.sol, contracts/PoolTest.sol, contracts/libraries/ProxyDeltas.sol, contracts/libraries/ReceiverWeights.sol, test/proxy-deltas.test.ts, test/receiver-weights.test.ts
Adds `ProxyDeltas`, which is a random access, iterable mapping between cycles and deltas of funds received by a proxy. It will be used when updating a proxy to determine how to update the downstream receivers' delta. It's an iterable version of a receiver's list of deltas, it stores the same data. Implementation and tests are a slightly modified version of the `ReceiverWeights` linked list. Some form of generics would be great in Solidity :shrug: `ProxyDeltas` aren't used in the production code yet, the next PR will do that, this PR is already quite big.
=> Add ProxyDeltas data structure

contracts/PoolTest.sol, contracts/libraries/ReceiverWeights.sol, test/pool.test.ts
Reverts the recent simplification of the non-pruning receiver weights iterator. The weights aren't guaranteed to be always pruned, it's a horrible coincidence that no tests caught it :grimacing:
=> Make non-pruning weights iterator skip zeroed items

contracts/Pool.sol, contracts/PoolTest.sol, contracts/libraries/ProxyDeltas.sol, contracts/libraries/ReceiverWeights.sol, test/receiver-weights.test.ts
Cuts 20-33 % of gas cost of iterating over mappings. The larger the mapping the bigger the saving.
Unfortunately it makes the iteration API even more complex. I've tried wrapping the swarm of parameters in a structure, but that forced it to be stored in memory leading to a considerable cost increase.
=> Cheaperators

CHANGELOG.md, DEVELOPING.md, package.json
Fixes https://github.com/radicle-dev/radicle-contracts/issues/65. When this PR is merged, I'll create the `v0.1.0` release from `master`'s head.
=> Introduce API versioning and a changelog

package.json
These are not available in the exported build that clients use, requiring
"all" clients to add these exact dependencies themselves in order to run
the 'deploy.ts' script. That should happen here instead to that it can
actually offer the functionality it proposes.
=> Move @uniswap and @ensdomains to "dependencies"

contracts/Governance/RadicleToken.sol, contracts/Registrar.sol, contracts/deploy/phase0.sol, src/deploy.ts, test/registrar.test.ts
Extracts the changes to RadicleToken and Registry from our fork at https://github.com/dapp-org/radicle-contracts, without including any of the testing infrastructure. Adapts the deployment contract and hardhat tests to the new Registry.
We have more tests at our fork, but they are left out of this PR as it would require more changes infrastructurally
=> add permit to RadicleToken and change Registry to commit reveal scheme

.buildkite/pipeline.yaml, ci/base-image/Dockerfile, ethregistrar/build/contracts/BaseRegistrar.json, ethregistrar/build/contracts/BaseRegistrarImplementation.json, hardhat.config.ts, package.json, yarn.lock
It can not be built on node >10 due to [an issue with scrypt](https://github.com/barrysteyn/node-scrypt/pull/197), which makes integrating this latest revision on Upstream unviable. We only need the JSON contract files so I have tracked them and pointed to those instead, and dropped that dependency.
=> chore: drop ethregistrar dependency

package.json
Both `@ensdomains/ens` and `@uniswap/v2-periphery` can by dev
dependencies. The packages are only used to build the project. The
build artifacts don’t contain references to the packages.
=> Demote production dependencies to dev deps

contracts/Pool.sol, src/deploy.ts
The switch of the pool contract from the block-based to the seconds-based time measurement hasn't been fully reflected in variable names. This PR fixes that.
=> Clean up variable names around pool

contracts/Pool.sol, contracts/TestDai.sol, src/deploy.ts, src/index.ts, src/utils.ts, test/pool.test.ts
This is a part of https://github.com/radicle-dev/radicle-contracts/issues/128 for the special case of Dai. This token isn't fully EIP-2612 compatible, but it's used in upstream.
This PR adds a basic implementation of Dai, which is just an ERC-20 with `permit`. The real Dai contract doesn't compile with modern versions of Solidity and there are no yarn packages with it already precompiled. We also need its API, which is available as a package, but it too needs old Solidity to work. An alternative would be to pull the Dai source code, compile it to a JSON and keep a copy of it in our repo. I think that with such simple contract it's clearer to maintain these few lines of code instead of a binary blob.
=> Add dai pool

src/index.ts
Re-export everything from `src/deploy` so that users of this package can select what contracts they want to deploy.
=> Re-export everything from `src/deploy`

contracts/ClaimsV2.sol, package.json, src/deploy-to-network.ts, src/deploy.ts
A part of https://github.com/radicle-dev/radicle-upstream/issues/2158. Removes the need to read calldata to understand the claim.
=> Add more data to Claimed event
