- contracts/VRad.sol
- package.json
- test/vrad.test.ts
- yarn.lock
We fix all style issues in this repo by running prettier once. We also
ensure that style is checked with prettier on CI.
> Run prettier now and on CI

- contracts/DummyEnsRegistry.sol
- contracts/DummyPriceOracle.sol
- contracts/PriceOracle.sol
- contracts/Registrar.sol
- contracts/StablePriceOracle.sol
- package.json
- test/registrar.test.ts
- test/support.ts
- test/vrad.test.ts
- tsconfig.json
- yarn.lock
This is an implementation of a basic ENS registrar.
The registration fee is based on a price feed oracle (Chainlink).
I've had to pull in some ENS code (the DummyEnsRegistrar) because of incompatibilities with our solidity version.
> Implement ENS Registrar

- contracts/DummyEnsRegistry.sol
- contracts/DummyPriceOracle.sol
- contracts/DummyRouter.sol
- contracts/Exchange.sol
- contracts/FixedWindowOracle.sol
- contracts/PriceOracle.sol
- contracts/Rad.sol
- contracts/Registrar.sol
- contracts/Router.sol
- contracts/StablePriceOracle.sol
- contracts/libraries/SafeMath.sol
- contracts/libraries/Uniswap.sol
- package.json
- test/registrar.test.ts
- yarn.lock
Add swap & burn on registration. Uses uniswap as the price oracle and exchange.
> Implement swap and burn

- contracts/Pool.sol
- test/pool.test.ts
It's a stub of a pool. Its' not doing much yet, allows storing and withdrawing ether.
> Add pool stub

- buidler.config.ts
- contracts/Pool.sol
- contracts/PoolTest.sol
- test/pool.test.ts
Adds a data structure, which is needed for the proper pool implementation (PR coming soon). I have a few questions in code comments.
> Add ReceiverWeights list

- .eslintrc.js
- package.json
- src/deploy.ts
- test/pool.test.ts
- test/support.ts
Also enforces function type signatures
> Fail on lint warnings

- package.json
- yarn.lock
We add all necessary production dependencies to use `src/deploy.ts`.
> Fix production dependencies

- src/deploy.ts
- test/registrar.test.ts
* Remove `deployDummy`. It’s not needed by upstream anymore
* Eliminate the `provider` argument from all deployment functions
* Ensure all transactions are OK
> Improve deployments

- package.json
- tsconfig.json
- yarn.lock
We add the necessary dependencies to use the Web3 contract bindings. We also ensure that TypeScript checks the bindings.
> Add and verify dependencies for web3 bindings

- buidler.config.ts
- contracts/Pool.sol
- contracts/PoolTest.sol
- src/deploy.ts
- test/pool.test.ts
Fixes https://github.com/radicle-dev/radicle-contracts/issues/15. A basic implementation of pools. Allows creating a personal pool and sending ETH. Tests are very shallow and extremely clunky, it's a stepping stone for a proper suite, but nothing more. I want to have this pushed out to let others play with it, I'll improve it as the next step.
CC: @NunoAlexandre
> Pool basic

- test/pool.test.ts
Now we have pool testing tools, which check more aspects of the contract state and allow tighter and more explicit control over what's going on.
Many of the tools are built around the design of the Buidler EVM and its mining behavior. Every call (use of a `view` or `pure` function) is done on the last block, which was mined. On the other hand every transaction (use of a non-`view` and non-`pure` funciton) first creates a new block, applies the transaction and then mines it. So we have:
```
contract.viewFn();    // executes with `block.number == 5`
contract.nonViewFn(); // executes with `block.number == 6`
contract.viewFn();    // executes with `block.number == 6`
contract.viewFn();    // executes with `block.number == 6`
contract.nonViewFn(); // executes with `block.number == 7` …
```
> Add stricter pool testing tools

- contracts/Pool.sol
- contracts/PoolTest.sol
Clean up `pool.sol`, no functionality added or changed.
> Pool fancy

- contracts/Pool.sol
- contracts/PoolTest.sol
- test/pool.test.ts
Fixes https://github.com/radicle-dev/radicle-contracts/issues/34 and https://github.com/radicle-dev/radicle-contracts/issues/29
> Get all recipients and funds per block of my pool 

- test/pool.test.ts
- test/support.ts
~Waiting for https://github.com/radicle-dev/radicle-contracts/pull/43, need a rebase after it's merged.~ :heavy_check_mark:
> Move common test utils to support.ts

- contracts/Pool.sol
- src/deploy.ts
- test/pool.test.ts
The first part of https://github.com/radicle-dev/radicle-contracts/issues/19. Splits the pool contract into an abstract, currency agnostic base and its derivative supporting Ether. This prepares ground for addition of another derivative supporting ERC-20.
> Pool abstract

- buidler.config.ts
They don't seem to make sense and aren't even used anywhere.
> Remove uniswap build artifacts

- contracts/Pool.sol
- test/pool.test.ts
Fixes https://github.com/radicle-dev/radicle-contracts/issues/19
> Add ERC-20 version of the pool

- contracts/Pool.sol
- test/pool.test.ts
Fixes https://github.com/radicle-dev/radicle-contracts/issues/55.
The `WITHDRAW_ALL` value is not `0`, because in the upcoming batching API we'll need to somehow convey that the user doesn't want to withdraw anything. Solidity doesn't make it easy to have optional arguments in the APIs, so the value `0` looks like the best bet to express that.
> Allow withrawal of all funds

- contracts/Pool.sol
- contracts/PoolTest.sol
- contracts/libraries/ReceiverWeights.sol
- test/pool.test.ts
Fixes https://github.com/radicle-dev/radicle-contracts/issues/16. It's pretty big and complex, but it's not dividable further in any reasonable way, sorry.
> Pool proxy

- test/pool.test.ts
A clean up and dedupllication of the test utils
> Unify test tools for ETH and ERC-20 pools

- test/pool.test.ts
Cleans up and speeds up pool tests:
- Deduplicates common pool tests as devised here: https://github.com/radicle-dev/radicle-contracts/pull/69#discussion_r543233583
- Caches pool constants. Querying for them ad-hoc was already starting to impact testing time. It would only get worse with wider usage of `updateSender`, which relies heavily on constants.
- Makes `PoolUser`s generic as they should be since inception ¯\\\_(ツ)_/¯
> Constants in tests

- contracts/VRad.sol
Just updated VRad for the new token contract.
> Update VRad contract to point to gov. token

- contracts/Pool.sol
- test/pool.test.ts
- test/support.ts
Finishes https://github.com/radicle-dev/radicle-contracts/issues/50.
> Remove pool sender updating functions other than updateSender

- contracts/Governance/Treasury.sol
- test/treasury.test.ts
> Create very simple treasury

- contracts/Governance/VestingToken.sol
Not much to say, pretty simple.
> Add token vesting cliff

- contracts/Registrar.sol
- src/deploy.ts
- test/registrar.test.ts
This allows the registrar fees to be changed. It also allows payment in Radicle.
> Updated registrar

- contracts/Registrar.sol
- src/deploy.ts
- test/registrar.test.ts
The Registrar contract itself won't be upgradable, but its parts will be!
> Make Registrar exchange, admin, oracle upgradable

- contracts/FailingOracle.sol
This oracle can be used in the registrar to effectively disable registration via ETH.
> A price oracle that always fails

- contracts/Registrar.sol
More or less inspired by https://github.com/ensdomains/ethregistrar/blob/master/contracts/BaseRegistrarImplementation.sol#L113
Closes #96
> Emit an event on registration

- contracts/Governance/Governor.sol
Use correct token supply, account for burn.
> Fix voting thresholds

- contracts/Governance/Treasury.sol
> Implement Treasury::setAdmin

- .prettierrc.js
- hardhat.config.ts
- src/deploy-to-network.ts
- src/deploy.ts
- test/attestations.test.ts
- test/governance.test.ts
- test/pool.test.ts
- test/proxy-deltas.test.ts
- test/proxy.test.ts
- test/radicle-token.test.ts
- test/receiver-weights.test.ts
- test/registrar.test.ts
- test/support.ts
- test/treasury.test.ts
- test/vesting-token.test.ts
The .sol files are already 100 characters wide, there's no need to keep .ts cramped. Removes .sol formatting options which don't change the defaults.
> Widen TS files to 100 chars

- contracts/Governance/VestingToken.sol
> VestingToken: audit fixes

- contracts/deploy/phase0.sol
- src/deploy-to-network.ts
- src/deploy.ts
- test/radicle-token.test.ts
Due to what I believe is a hardhat bug (https://github.com/nomiclabs/hardhat/issues/1227) a few tests aren't verifying transaction rejection messages anymore.
> Create factory contract for phase0

- contracts/Governance/Governor.sol
- contracts/Governance/Timelock.sol
* Couldn't use `calldata` everywhere, as it says "callstack too deep"  on `propose`.
* I actually changed the threshold logic, because it doesn't match the other threshold check. So I think the error message was correct, and the logic was wrong. See: https://github.com/radicle-dev/radicle-contracts/blob/master/contracts/Governance/Governor.sol#L299 -- without this change, if you have exactly the threshold, you can neither propose nor cancel..
> Optional improvements from audit

- contracts/Governance/Governor.sol
- contracts/Governance/RadicleToken.sol
- Make `token` and `timelock` immutable in the `Governor`
- Fix the EIP-2612 breakage introduced in https://github.com/radicle-dev/radicle-contracts/pull/120
> Final tweaks

- CHANGELOG.md
- contracts/Claims.sol
- src/deploy.ts
Implementation of a smart contract for https://github.com/radicle-dev/radicle-link/pull/557
> Add Link ID claims contract

- DEVELOPING.md
It wasn't clear for me where to get the docker image tag from after setting a non-existent one.
> developing: clarify how to update docker image

- contracts/Pool.sol
Clean up the obsolete pool contract code structure. The modifier didn't DRY anything anymore while obscuring the logic flow.
> Remove the suspendPayments modifier

- contracts/Pool.sol
- test/pool.test.ts
Closes https://github.com/radicle-dev/radicle-contracts/issues/51. Now events are enough to recreate the whole donations history, the current state and all known information about the future.
> Pool events proxy

- CHANGELOG.md
- contracts/Pool.sol
- test/pool.test.ts
Adds more pool events needed to switch from polling the contract state to listening to the events: https://github.com/orgs/radicle-dev/projects/18#card-54079531
> More events

- contracts/Pool.sol
This is needed to compile the funding pool using Truffle
> Fix pool function 'now' colliding with a built-in

- README.md
So it is documented somewhere.
> Add RAD token contract addresses to readme
